name: Module Release
on:
  repository_dispatch:
    types: [bazelboost-module-release]
jobs:
  create-pr:
    name: add ${{ github.event.client_payload.repo }} ${{ github.event.client_payload.tag_name }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache      
      - uses: actions/setup-go@v4
      - run: go install github.com/bazelbuild/buildtools/buildozer@latest
      - uses: actions/checkout@v4
        with:
          repository: bazelboost/registry
      - run: bazelisk run --config=ci //tools:add_module_version -- -archive="${{ github.event.client_payload.archive }}"
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b add-${{ github.event.client_payload.repo }}-${{ github.event.client_payload.tag_name }}
          git add -A
          git commit -m "chore: add ${{ github.event.client_payload.repo }} ${{ github.event.client_payload.tag_name }}"
          git push origin -u add-${{ github.event.client_payload.repo }}-${{ github.event.client_payload.tag_name }}
      - run: gh pr create -R bazelboost/registry --fill -B main
        env:
          GH_TOKEN: ${{ github.token }}
